### ISSUE TITLE
iOS - sdksInitializedAndReady - User is not online

### ISSUE THREAD

**Issue by raphaelguye** [citrix/citrix-mam-sdks#54]
Following your official documentation, I setup the MAM sdk in the [AppDelegate](https://gist.github.com/raphaelguye/b797bd8da69c76fc6537f88706c38c54) of our project. It's a SwiftUI project targeting iOS 15. 

The MDX bundle is also created following your recommandation. 

The problem occurs in the implementation of your callback method `sdksInitializedAndReady`:

- At the first launch of the app, everything is working fine. SDK initialization is success and the user is online.
- Since the second time I start the app. The SDK initialization is still success but the user is **NOT** online.

That's not clear to me what does this callback method, do you have more explanations?
Do you know why the user seems to not be online?

**Comment by GeroHerkenrath** [comment]
I'm not from the citrix team, but perhaps I can help a bit here until they show up. 😃 

I'm not sure what you mean with "online", are you talking about the Micro-VPN the `CTXMAMNetwork.framework` part of the SDK can establish? Because that's not what the method does.

In fact, it's quite literal, it initializes the SDK, meaning all the various method swizzling is performed once you call it. You can see that in the console logs. For the VPN connection, for example, the various methods of `URLSession` (and probably some others that I forgot at the moment) are swizzled with wrapping implementations that establish a VPN connection as needed when you try to load something from a remote endpoint that's in your VPN. 

At least that's how I _guess_ the SDK does it (feel free to correct me, Citrix people). If needed, that includes a "jump to and from" the Secure Hub app, at least in my setup (no idea if there are other configurations that work differently). The point is that "going online" (if you mean what I assume you do with that) happens automatically.

I further assume that behind the scenes, the swizzling kind of reroutes your URLs through an endpoint of your protected network that only accepts requests (and reroutes them back to the endpoint you want to access) when you have a valid OAuth2 token (or something equivalent). This is what the Secure Hub app "gets" for you when you jump into it. However, the SDK seems to properly cache it in the keychain as long as it's still valid, so that's why in an immediately subsequent launch of the app you don't see a jump to the Secure Hub app again. The previously gained token might still be valid.

I don't know what you mean with "seems not to be online" here, though, you're kind of vague. Any requests that you make go through, or not?

**Comment by raphaelguye** [comment]
There is a delegate [CTXMAMCoreSdkDelegate](https://developer.cloud.com/citrixworkspace/mobile-application-integration/mam-sdk-for-ios-and-ipados/docs/ctxmamcore.h) to received callbacks from the SDK.
One of its method is `func sdksInitializedAndReady(_ online: Bool)`.

Thank you for your explanations, it make sens I guess. It would explain why the parameter `online` is true only the first time... But in that case I don't know why they called it `online`.

**Comment by GeroHerkenrath** [comment]
That is indeed a good question. I haven't actively used the delegate myself yet as in our project we have no need to do much with the SDK except rely on its micro-VPN.

I admit I made a lot of assumptions, so perhaps there's more to it. Would be great if a Citrix dev could comment, especially since the documentation is a bit... thin... 🥲 

Glad I could offer at least some explanations (btw, I have mostly deduced this from using the SDK and having done things like this myself in the past, albeit mostly in unit and UI tests).

**Comment by jaspreet1** [comment]
Hi @raphaelguye and @GeroHerkenrath,
Apologies for the delayed response on this.

With the introduction of the new initializeSDKsWithCompletionBlock: API, implementing sdksInitializedAndReady: delegate method seems to be redundant in some ways, as the completion block of the new API would be a reliable way to know if SDKs were initialized or not. 
We have already planned to deprecate this sdksInitializedAndReady delegate method in our subsequent public releases.

In case you are curious about the "online" param, I can give some idea about this.
The online value would return "YES", whenever CitrixMAM SDK receives app information (including app policies) update from the CEM server. In initial CitrixMAM releases, CitrixMAM SDK receives/refreshes this app information at the start of the app, but in recent releases, this is not true, so that's why you noticed the "online" arg value is "NO". 

Also, I understand currently the online public documentation may not cover enough details explaining the use and behavior of the APIs, I really appreciate your feedback. Just want to let you know that we are already working on improving these, including the sample app.

Hope this helps. Let me know if I missed addressing any questions.
